from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(968, 870)
        font = QtGui.QFont()
        font.setPointSize(30)
        MainWindow.setFont(font)
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.estimations_grid_layout = QtWidgets.QGridLayout(self.centralwidget)
        self.estimations_grid_layout.setObjectName("estimations_grid_layout")
        self.mainWindow_grid_layout = QtWidgets.QGridLayout()
        self.mainWindow_grid_layout.setObjectName("mainWindow_grid_layout")
        self.description_gridlayout = QtWidgets.QGridLayout()
        self.description_gridlayout.setObjectName("description_gridlayout")
        self.description_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.description_label.setFont(font)
        self.description_label.setAlignment(QtCore.Qt.AlignCenter)
        self.description_label.setObjectName("description_label")
        self.description_gridlayout.addWidget(self.description_label, 0, 0, 1, 1)
        self.description_text_edit = QtWidgets.QTextEdit(self.centralwidget)
        self.description_text_edit.setObjectName("description_text_edit")
        self.description_gridlayout.addWidget(self.description_text_edit, 1, 0, 1, 2)
        self.mainWindow_grid_layout.addLayout(self.description_gridlayout, 5, 0, 1, 7)
        self.genre_grid_layout = QtWidgets.QGridLayout()
        self.genre_grid_layout.setObjectName("genre_grid_layout")
        self.genre_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.genre_label.setFont(font)
        self.genre_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.genre_label.setObjectName("genre_label")
        self.genre_grid_layout.addWidget(self.genre_label, 0, 0, 1, 2)
        self.genre_area = QtWidgets.QScrollArea(self.centralwidget)
        self.genre_area.setWidgetResizable(True)
        self.genre_area.setObjectName("genre_area")
        self.genre_scroll_area_widget_contents = QtWidgets.QWidget()
        self.genre_scroll_area_widget_contents.setGeometry(QtCore.QRect(0, 0, 191, 85))
        self.genre_scroll_area_widget_contents.setMaximumSize(QtCore.QSize(191, 16777215))
        self.genre_scroll_area_widget_contents.setObjectName("genre_scroll_area_widget_contents")
        self.genres_vertical_layout = QtWidgets.QWidget(self.genre_scroll_area_widget_contents)
        self.genres_vertical_layout.setGeometry(QtCore.QRect(0, 0, 191, 71))
        self.genres_vertical_layout.setObjectName("genres_vertical_layout")
        self.genres = QtWidgets.QVBoxLayout(self.genres_vertical_layout)
        self.genres.setContentsMargins(0, 0, 0, 0)
        self.genres.setObjectName("genres")
        self.genre_area.setWidget(self.genre_scroll_area_widget_contents)
        self.genre_grid_layout.addWidget(self.genre_area, 1, 0, 1, 2)
        self.mainWindow_grid_layout.addLayout(self.genre_grid_layout, 4, 0, 1, 4)
        self.studio_grid_layout = QtWidgets.QGridLayout()
        self.studio_grid_layout.setObjectName("studio_grid_layout")
        self.studio_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.studio_label.setFont(font)
        self.studio_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.studio_label.setObjectName("studio_label")
        self.studio_grid_layout.addWidget(self.studio_label, 0, 0, 1, 1)
        self.studios_area = QtWidgets.QScrollArea(self.centralwidget)
        self.studios_area.setWidgetResizable(True)
        self.studios_area.setObjectName("studios_area")
        self.studio_scroll_area_widget_contents = QtWidgets.QWidget()
        self.studio_scroll_area_widget_contents.setGeometry(QtCore.QRect(0, 0, 437, 85))
        self.studio_scroll_area_widget_contents.setObjectName("studio_scroll_area_widget_contents")
        self.studio_verticalLayout = QtWidgets.QWidget(self.studio_scroll_area_widget_contents)
        self.studio_verticalLayout.setGeometry(QtCore.QRect(0, 0, 191, 71))
        self.studio_verticalLayout.setObjectName("studio_verticalLayout")
        self.studios = QtWidgets.QVBoxLayout(self.studio_verticalLayout)
        self.studios.setContentsMargins(0, 0, 0, 0)
        self.studios.setObjectName("studios")
        self.studios_area.setWidget(self.studio_scroll_area_widget_contents)
        self.studio_grid_layout.addWidget(self.studios_area, 1, 0, 1, 1)
        self.mainWindow_grid_layout.addLayout(self.studio_grid_layout, 4, 4, 1, 3)
        self.mediamark_main_label = QtWidgets.QLabel(self.centralwidget)
        self.mediamark_main_label.setEnabled(True)
        self.mediamark_main_label.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        self.mediamark_main_label.setFont(font)
        self.mediamark_main_label.setObjectName("mediamark_main_label")
        self.mainWindow_grid_layout.addWidget(self.mediamark_main_label, 0, 1, 1, 6)
        self.basic_parameters_layout = QtWidgets.QGridLayout()
        self.basic_parameters_layout.setObjectName("basic_parameters_layout")
        self.name_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.name_label.setFont(font)
        self.name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.name_label.setObjectName("name_label")
        self.basic_parameters_layout.addWidget(self.name_label, 0, 0, 1, 1)
        self.name_text_edit = QtWidgets.QTextEdit(self.centralwidget)
        self.name_text_edit.setObjectName("name_text_edit")
        self.basic_parameters_layout.addWidget(self.name_text_edit, 1, 0, 1, 5)
        self.date_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.date_label.setFont(font)
        self.date_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.date_label.setObjectName("date_label")
        self.basic_parameters_layout.addWidget(self.date_label, 3, 0, 1, 3)
        self.episode_count_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.episode_count_label.setFont(font)
        self.episode_count_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.episode_count_label.setObjectName("episode_count_label")
        self.basic_parameters_layout.addWidget(self.episode_count_label, 4, 0, 1, 3)
        self.type_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.type_label.setFont(font)
        self.type_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.type_label.setObjectName("type_label")
        self.basic_parameters_layout.addWidget(self.type_label, 5, 0, 1, 3)
        self.age_rating_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.age_rating_label.setFont(font)
        self.age_rating_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.age_rating_label.setObjectName("age_rating_label")
        self.basic_parameters_layout.addWidget(self.age_rating_label, 6, 0, 1, 3)
        self.date_edit = QtWidgets.QDateEdit(self.centralwidget)
        self.date_edit.setDate(QtCore.QDate(2024, 1, 1))
        self.date_edit.setObjectName("date_edit")
        self.basic_parameters_layout.addWidget(self.date_edit, 3, 3, 1, 2)
        self.episode_count_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.episode_count_line_edit.setObjectName("episode_count_line_edit")
        self.basic_parameters_layout.addWidget(self.episode_count_line_edit, 4, 3, 1, 2)
        self.type_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.type_combobox.setObjectName("type_combobox")
        self.basic_parameters_layout.addWidget(self.type_combobox, 5, 3, 1, 2)
        self.age_rating_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.age_rating_combobox.setObjectName("age_rating_combobox")
        self.basic_parameters_layout.addWidget(self.age_rating_combobox, 6, 3, 1, 2)
        self.mainWindow_grid_layout.addLayout(self.basic_parameters_layout, 2, 0, 1, 5)
        self.estimation_grid_layouts = QtWidgets.QGridLayout()
        self.estimation_grid_layouts.setObjectName("estimation_grid_layouts")
        self.accurent_mark_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.accurent_mark_label.setFont(font)
        self.accurent_mark_label.setAlignment(QtCore.Qt.AlignCenter)
        self.accurent_mark_label.setObjectName("accurent_mark_label")
        self.estimation_grid_layouts.addWidget(self.accurent_mark_label, 0, 2, 1, 1)
        self.estimation_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        self.estimation_button.setFont(font)
        self.estimation_button.setObjectName("estimation_button")
        self.estimation_grid_layouts.addWidget(self.estimation_button, 6, 2, 1, 1)
        self.estimation_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(48)
        font.setBold(False)
        font.setItalic(False)
        self.estimation_label.setFont(font)
        self.estimation_label.setStyleSheet("font: 48pt \"MS Shell Dlg 2\";")
        self.estimation_label.setAlignment(QtCore.Qt.AlignCenter)
        self.estimation_label.setObjectName("estimation_label")
        self.estimation_grid_layouts.addWidget(self.estimation_label, 1, 1, 4, 3)
        self.full_estimation_label = QtWidgets.QLabel(self.centralwidget)
        self.full_estimation_label.setAlignment(QtCore.Qt.AlignCenter)
        self.full_estimation_label.setObjectName("full_estimation_label")
        self.estimation_grid_layouts.addWidget(self.full_estimation_label, 5, 1, 1, 3)
        self.mainWindow_grid_layout.addLayout(self.estimation_grid_layouts, 2, 5, 1, 2)
        self.estimations_grid_layout.addLayout(self.mainWindow_grid_layout, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 968, 26))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.load_action = QtWidgets.QAction(MainWindow)
        self.load_action.setObjectName("load_action")
        self.save_action = QtWidgets.QAction(MainWindow)
        self.save_action.setObjectName("save_action")
        self.menu.addAction(self.load_action)
        self.menu.addAction(self.save_action)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.description_label.setText(_translate("MainWindow", "<html><head/><body><p>Описание</p></body></html>"))
        self.genre_label.setText(_translate("MainWindow", "Жанры"))
        self.studio_label.setText(_translate("MainWindow", "Студия"))
        self.mediamark_main_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">MediaMark</span></p></body></html>"))
        self.name_label.setText(_translate("MainWindow", "Название"))
        self.date_label.setText(_translate("MainWindow", "Год выхода"))
        self.episode_count_label.setText(_translate("MainWindow", "Количество эпизодов"))
        self.type_label.setText(_translate("MainWindow", "<html><head/><body><p>Тип медиаконтента</p></body></html>"))
        self.age_rating_label.setText(_translate("MainWindow", "Возрастной рейтинг"))
        self.date_edit.setDisplayFormat(_translate("MainWindow", "yyyy"))
        self.accurent_mark_label.setText(_translate("MainWindow", "Оценка"))
        self.estimation_button.setText(_translate("MainWindow", "Оценить"))
        self.estimation_label.setText(_translate("MainWindow", "0.00"))
        self.full_estimation_label.setText(_translate("MainWindow", "0.00"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.load_action.setText(_translate("MainWindow", "Загрузить"))
        self.save_action.setText(_translate("MainWindow", "Сохранить как"))
